import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const ROOT = path.resolve(new URL("..", import.meta.url).pathname);
const pkgPath = require.resolve("lucide/package.json");
const lucideRoot = path.dirname(pkgPath);
const lucidePkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
const { icons } = require("lucide");

function pascalToKebab(name) {
  return name
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/_/g, "-")
    .toLowerCase();
}

const names = Array.from(new Set(Object.keys(icons).map(pascalToKebab))).sort();
const outAssets = path.join(ROOT, "docs", "assets");
const outVendor = path.join(outAssets, "vendor");
fs.mkdirSync(outVendor, { recursive: true });

const vendorBundle = fs
  .readFileSync(path.join(lucideRoot, "dist", "umd", "lucide.min.js"), "utf8")
  .replace(/\n?\/\/# sourceMappingURL=lucide\.min\.js\.map\s*$/, "\n");
fs.writeFileSync(path.join(outVendor, "lucide.min.js"), vendorBundle);
fs.rmSync(path.join(outVendor, "lucide.min.js.map"), { force: true });

const manifest = `/* Generated by scripts/build-icons.mjs from lucide@${lucidePkg.version}. */\n` +
  `window.DS_LUCIDE_ICON_MANIFEST = ${JSON.stringify({
    name: "lucide",
    version: lucidePkg.version,
    source: "https://lucide.dev",
    license: lucidePkg.license,
    count: names.length,
    names,
  }, null, 2)};\n`;

fs.writeFileSync(path.join(outAssets, "lucide-icon-manifest.js"), manifest);

console.log(`Generated Lucide icon assets: ${names.length} names from lucide@${lucidePkg.version}`);
